# Generated by Django 6.0 on 2025-12-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('category', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
